- name: Single branch Pipeline Setup for App Components
  ansible.builtin.include_tasks:
    file: sp_jobs.yml
  loop: "{{ sp_jobs }}"

- name: Multi branch Pipeline Setup for App Components
  ansible.builtin.include_tasks:
    file: mp_jobs.yml
  loop: "{{ mp_jobs }}"
